version: '3.4'

services:

  civicrm:
    image: michaelmcandrew/civicrm-buildkit
    hostname: civicrm
    environment:
      TERM: xterm-color
      APACHE_RUN_USER: buildkit
    links:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - buildkit:/buildkit
      - ./build:/buildkit/build
      - ./:/nasc
      - amp:/buildkit/.amp
      - bower-cache:/buildkit/.cache/bower
      - composer-cache:/buildkit/.composer
      - drush-cache:/buildkit/.drush
      - npm-cache:/buildkit/.npm
      - git-cache:/buildkit/app/tmp/git-cache

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: buildkit
    volumes:
      - mysql:/var/lib/mysql

volumes:
  amp:
  buildkit:
  bower-cache:
  composer-cache:
  drush-cache:
  git-cache:
  npm-cache:
  mysql:
